spring:
  datasource:
    password: root
    url: jdbc:mysql://mysql:3306/fullstack
    username: test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
     hibernate:
      format_sql: true
     # dialect: org.hibernate.dialect.MySQLDialect
     
     
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        exclude:
        - beans
      base-path: /myactuator
        
        
  endpoint:
    shutdown:
      enabled: true
   
    
  info:
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
      
      
    
      
info:
  createdBy: Sharad Rajore
  modified : 22June22
  
  
#logging:
#  level:
#    com:
#     zensar: debug
      
  

  
  
      
 
    
        
     
      

    

      
      
      

